export interface StockMediaItem {
  id: string;
  name: string;
  category: 'restaurants' | 'retail' | 'clinics' | 'corporate' | 'widgets' | 'tickers';
  categoryLabel: string;
  fileType: 'image' | 'video' | 'web_url' | 'ticker_text';
  fileUrl: string;
  thumbnailUrl: string;
  durationSeconds: number;
  description: string;
  fileSizeBytes: number;
  width?: number;
  height?: number;
  tags: string[];
  customTickerText?: string;
  aspectRatio?: '16:9' | '9:16';
}

export const STOCK_MEDIA_CATALOG: StockMediaItem[] = [
  // ==========================================
  // 1. المطاعم والمقاهي (Restaurants & Cafes)
  // ==========================================
  {
    id: 'stock-coffee-video',
    name: 'فيديو تحضير القهوة المختصة واللاتيه آرت',
    category: 'restaurants',
    categoryLabel: 'مطاعم ومقاهي',
    fileType: 'video',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 15,
    description: 'فيديو احترافي لتحضير القهوة والضيافة بدقة عالية للشاشات الأفقية',
    fileSizeBytes: 14200000,
    width: 1920,
    height: 1080,
    tags: ['قهوة', 'كافيه', 'فيديو', 'ترويجي'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-burger-video',
    name: 'فيديو شوي البرجر والوجبات السريعة الفاخرة',
    category: 'restaurants',
    categoryLabel: 'مطاعم ومقاهي',
    fileType: 'video',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 15,
    description: 'عرض متحرك جذاب للوجبات السريعة وشوي البرجر على اللهب',
    fileSizeBytes: 15400000,
    width: 1920,
    height: 1080,
    tags: ['مطاعم', 'برجر', 'وجبات_سريعة', 'فيديو'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-pizza-video',
    name: 'فيديو البيتزا الإيطالية الطازجة من الفرن',
    category: 'restaurants',
    categoryLabel: 'مطاعم ومقاهي',
    fileType: 'video',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 15,
    description: 'فيديو ترويجي لصناعة البيتزا الطازجة والمخبوزات الساخنة',
    fileSizeBytes: 13800000,
    width: 1920,
    height: 1080,
    tags: ['بيتزا', 'مطاعم', 'مخبوزات'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-menu-board-img',
    name: 'لوحة منيو قائمة الوجبات والمشروبات (4K Menu Board)',
    category: 'restaurants',
    categoryLabel: 'مطاعم ومقاهي',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 12,
    description: 'تصميم فخم لقائمة الطعام والمشروبات جاهز للعرض الدائم على شاشات المطاعم',
    fileSizeBytes: 3450000,
    width: 1920,
    height: 1080,
    tags: ['منيو', 'مطاعم', 'شاشات_عرض'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-desserts-img',
    name: 'بوستر الحلويات والآيس كريم والوافل الفرنسي',
    category: 'restaurants',
    categoryLabel: 'مطاعم ومقاهي',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 10,
    description: 'بوستر تسويقي لعروض الحلويات والمثلجات والقهوة الباردة',
    fileSizeBytes: 2890000,
    width: 1920,
    height: 1080,
    tags: ['حلويات', 'كافيه', 'صيف'],
    aspectRatio: '16:9',
  },

  // ==========================================
  // 2. المتاجر والتجزئة والأزياء (Retail & Fashion)
  // ==========================================
  {
    id: 'stock-fashion-video',
    name: 'فيديو عروض الأزياء والموضة العالمية',
    category: 'retail',
    categoryLabel: 'متاجر وتجزئة',
    fileType: 'video',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 15,
    description: 'فيديو سينمائي حديث لعرض تشكيلات الملابس والإكسسوارات في واجهات المتاجر',
    fileSizeBytes: 16100000,
    width: 1920,
    height: 1080,
    tags: ['أزياء', 'تسوق', 'ملابس', 'فيديو'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-sale-poster-img',
    name: 'بوستر التخفيضات الكبرى - خصم حتى 50%',
    category: 'retail',
    categoryLabel: 'متاجر وتجزئة',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 10,
    description: 'إعلان ترويجي صارخ للتخفيضات الموسمية والجمعة البيضاء',
    fileSizeBytes: 2980000,
    width: 1920,
    height: 1080,
    tags: ['عروض', 'خصومات', 'تسوق', 'متاجر'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-perfume-img',
    name: 'بوستر العطور الفاخرة والساعات الأنيقة',
    category: 'retail',
    categoryLabel: 'متاجر وتجزئة',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 10,
    description: 'إعلان فاخر لمنتجات العناية والعطور والهدايا',
    fileSizeBytes: 3100000,
    width: 1920,
    height: 1080,
    tags: ['عطور', 'هدايا', 'فاخر'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-tools-img',
    name: 'بوستر الأجهزة المنزلية وأدوات الصيانة',
    category: 'retail',
    categoryLabel: 'متاجر وتجزئة',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 10,
    description: 'تصميم مميز لمتاجر الأدوات والمعدات ومستلزمات البناء والمنازل',
    fileSizeBytes: 3200000,
    width: 1920,
    height: 1080,
    tags: ['أدوات', 'منزل', 'صيانة'],
    aspectRatio: '16:9',
  },

  // ==========================================
  // 3. العيادات والمراكز الطبية (Clinics & Healthcare)
  // ==========================================
  {
    id: 'stock-clinic-video',
    name: 'فيديو التوعية الصحية والرعاية الطبية الشاملة',
    category: 'clinics',
    categoryLabel: 'عيادات وصحة',
    fileType: 'video',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 20,
    description: 'فيديو هادئ مخصص لشاشات صالات الانتظار والعيادات لتقليل توتر المراجعين',
    fileSizeBytes: 18900000,
    width: 1920,
    height: 1080,
    tags: ['عيادات', 'صحة', 'توعية', 'فيديو'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-dental-img',
    name: 'بوستر العناية بالأسنان وابتسامة هوليوود',
    category: 'clinics',
    categoryLabel: 'عيادات وصحة',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 12,
    description: 'إعلان لخدمات تبييض وتجميل وتقويم الأسنان في مراكز طب الأسنان',
    fileSizeBytes: 2750000,
    width: 1920,
    height: 1080,
    tags: ['أسنان', 'تجميل', 'عيادة'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-medical-checkup-img',
    name: 'بوستر باقات الفحص الدوري الشامل للأفراد والأسرة',
    category: 'clinics',
    categoryLabel: 'عيادات وصحة',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 12,
    description: 'بوستر إرشادي لمواعيد وباقات الفحص الشامل والمختبرات الطبية',
    fileSizeBytes: 2600000,
    width: 1920,
    height: 1080,
    tags: ['فحص', 'مختبر', 'مستشفى', 'رعاية'],
    aspectRatio: '16:9',
  },

  // ==========================================
  // 4. الشركات والتقنية والعقارات (Corporate & Tech)
  // ==========================================
  {
    id: 'stock-tech-ai-video',
    name: 'فيديو الذكاء الاصطناعي والتحول الرقمي للشركات',
    category: 'corporate',
    categoryLabel: 'شركات وتقنية',
    fileType: 'video',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 15,
    description: 'فيديو تقني مبهر لشاشات بهو الاستقبال والمقرات الرئيسية وقاعات المؤتمرات',
    fileSizeBytes: 17500000,
    width: 1920,
    height: 1080,
    tags: ['تقنية', 'ذكاء_اصطناعي', 'شركات'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-realestate-video',
    name: 'فيديو الأبراج السكنية والمشاريع العقارية الفاخرة',
    category: 'corporate',
    categoryLabel: 'شركات وتقنية',
    fileType: 'video',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 15,
    description: 'عرض عقاري واستثماري متميز لأبراج المدن والمجمعات الحديثة',
    fileSizeBytes: 16800000,
    width: 1920,
    height: 1080,
    tags: ['عقارات', 'أبراج', 'استثمار'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-business-summit-img',
    name: 'بوستر مؤتمر الأعمال والابتكار السنوي 2026',
    category: 'corporate',
    categoryLabel: 'شركات وتقنية',
    fileType: 'image',
    fileUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1920&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 10,
    description: 'تصميم رسمي لمؤتمرات الأعمال، وجداول الجلسات والمتحدثين',
    fileSizeBytes: 3150000,
    width: 1920,
    height: 1080,
    tags: ['مؤتمرات', 'أعمال', 'فعاليات'],
    aspectRatio: '16:9',
  },

  // ==========================================
  // 5. صفحات ويب وأدوات حية (Live Widgets & URLs)
  // ==========================================
  {
    id: 'stock-weather-widget',
    name: 'ودجة طقس العالم ودرجات الحرارة المباشرة',
    category: 'widgets',
    categoryLabel: 'أدوات ويب',
    fileType: 'web_url',
    fileUrl: 'https://weather.com',
    thumbnailUrl: 'https://images.unsplash.com/photo-1592210454359-9043f067919b?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 30,
    description: 'تضمين مباشر لرادار الطقس وتوقعات درجات الحرارة لمدن المملكة والخليج',
    fileSizeBytes: 1024,
    tags: ['طقس', 'موقع', 'مباشر'],
    aspectRatio: '16:9',
  },
  {
    id: 'stock-news-portal',
    name: 'شاشة البث الإخباري والمتابعة الحية',
    category: 'widgets',
    categoryLabel: 'أدوات ويب',
    fileType: 'web_url',
    fileUrl: 'https://www.alarabiya.net',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=600&q=75',
    durationSeconds: 45,
    description: 'عرض مباشر لصفحة الأخبار والتحديثات الاقتصادية العاجلة',
    fileSizeBytes: 2048,
    tags: ['أخبار', 'عاجل', 'مباشر'],
    aspectRatio: '16:9',
  },

  // ==========================================
  // 6. أشرطة إخبارية ونصوص متحركة (Ready Tickers)
  // ==========================================
  {
    id: 'stock-ticker-restaurant',
    name: 'شريط عروض المطاعم والوجبات السريعة',
    category: 'tickers',
    categoryLabel: 'نصوص وأشرطة',
    fileType: 'ticker_text',
    fileUrl: '',
    thumbnailUrl: '',
    customTickerText: '🍔 عرض الغداء المميز: اطلب وجبة برجر دبل واحصل على مقبلات ومشروب مجاناً • نكهاتنا لا تُقاوم • خدمة التوصيل السريع متاحة عبر التطبيق',
    durationSeconds: 15,
    description: 'نص إعلاني متحرك خاص بالمطاعم والكافيهات',
    fileSizeBytes: 256,
    tags: ['شريط', 'مطاعم', 'عروض'],
  },
  {
    id: 'stock-ticker-clinic',
    name: 'شريط إرشادات ومواعيد العيادات والمستشفيات',
    category: 'tickers',
    categoryLabel: 'نصوص وأشرطة',
    fileType: 'ticker_text',
    fileUrl: '',
    thumbnailUrl: '',
    customTickerText: '🩺 مرحباً بكم في المركز الطبي • نرجو من مراجعينا الكرام التوجه لغرفة القياسات الحيوية قبل الدخول للطبيب • مواعيد العيادات المسائية حتى 10:00 م',
    durationSeconds: 15,
    description: 'نص توعوي تنظيمي لشاشات صالات الانتظار والمستشفيات',
    fileSizeBytes: 256,
    tags: ['شريط', 'عيادات', 'صحة'],
  },
  {
    id: 'stock-ticker-retail',
    name: 'شريط التخفيضات الكبرى وعروض الموسم',
    category: 'tickers',
    categoryLabel: 'نصوص وأشرطة',
    fileType: 'ticker_text',
    fileUrl: '',
    thumbnailUrl: '',
    customTickerText: '🛍️ عروض الصيف الكبرى: خصومات حصرية تصل إلى 50% على جميع التشكيلات الجديدة • العرض ساري حتى نفاد الكمية في جميع الفروع',
    durationSeconds: 15,
    description: 'شريط مبيعات جذاب لتحفيز المشترين في المتاجر',
    fileSizeBytes: 256,
    tags: ['شريط', 'تخفيضات', 'مبيعات'],
  },
  {
    id: 'stock-ticker-welcome',
    name: 'شريط الترحيب والضيافة للشركات والمقرات',
    category: 'tickers',
    categoryLabel: 'نصوص وأشرطة',
    fileType: 'ticker_text',
    fileUrl: '',
    thumbnailUrl: '',
    customTickerText: '🌟 نرحب بضيوفنا وزوارنا الكرام في مقر الشركة • نتمنى لكم يوماً حافلاً بالنجاح والإنجازات • شبكة Wi-Fi مجانية متاحة للزوار باسم Guest-WiFi',
    durationSeconds: 15,
    description: 'شريط ترحيبي رسمي للمقرات الرئيسية وبهو الاستقبال',
    fileSizeBytes: 256,
    tags: ['شريط', 'ترحيب', 'شركات'],
  }
];
